release:
        only:
                - master
        script:
                - find subprojects -type d -empty -delete
                - meson setup build --reconfigure -Dbuild_profile=release --unity=on -Dunity_size=45
                - nice -n 12 meson compile -C build
                - nice -n 12 meson test -C build
                - mv build/circle .
                - iconv -c -f utf8 -t koi8-r changelog > changelog.koi8
                - mv changelog.koi8 changelog
        cache:
                key: "$CI_BUILD_REF_NAME/Release"
                untracked: true
                paths:
                        - build/
        artifacts:
                name: "circle-release"
                paths:
                        - circle
                        - changelog
                expire_in: 1 week
        tags:
                - builder

debug:
        script:
                - find subprojects -type d -empty -delete
                - meson setup build --reconfigure -Dbuild_profile=debug --unity=on -Dunity_size=45
                - nice -n 12 meson compile -C build
                - nice -n 12 meson test -C build
                - mv build/circle .
                - iconv -c -f utf8 -t koi8-r changelog > changelog.koi8
                - mv changelog.koi8 changelog
        cache:
                key: "$CI_BUILD_REF_NAME/Debug"
                untracked: true
                paths:
                        - build/
        when: manual
        artifacts:
                name: "circle-debug"
                paths:
                        - circle
                        - changelog
                expire_in: 1 week
        tags:
                - builder

deploy-debug:
        stage: deploy
        dependencies:
                - debug
        script:
                - rm -rf ${BYLINS_DEBUG_HOME}/circle || true
                - cp -af circle ${BYLINS_DEBUG_HOME}
                - rm -rf ${BYLINS_DEBUG_HOME}/changelog || true
                - cp -af changelog ${BYLINS_DEBUG_HOME}
                - touch ${BYLINS_DEBUG_HOME}/lib/external.triggers/touch.me.for.reboot
        when: manual
        tags:
                - mirror

deploy-release:
        only:
                - master
        stage: deploy
        dependencies:
                - release
        script:
                - rm -rf ${BYLINS_RELEASE_HOME}/circle || true
                - cp -af circle ${BYLINS_RELEASE_HOME}
                - rm -rf ${BYLINS_RELEASE_HOME}/changelog || true
                - cp -af changelog ${BYLINS_RELEASE_HOME}
                - touch ${BYLINS_RELEASE_HOME}/lib/external.triggers/touch.me.for.reboot
        when: manual
        tags:
                - mirror