#!/bin/bash
PORT=4000
ulimit -c unlimited

# Default flags to pass to the MUD server (see admin.txt for a description
# of all flags).
FLAGS='-q'

#############################################################################

while ( : ) do

  DATE=`date`
  echo "autorun starting game $DATE" >> syslog
  echo "running bin/circle $FLAGS $PORT" >> syslog

  build/circle $FLAGS $PORT 
  mv syslog.CRASH.1 syslog.CRASH.2
  mv syslog.CRASH syslog.CRASH.1
  tail -1000 syslog > syslog.CRASH

  fgrep "self-delete" syslog >> log/delete
  fgrep "death trap" syslog >> log/dts
  fgrep "killed" syslog >> log/rip
  fgrep "Running" syslog >> log/restarts
  fgrep "advanced" syslog >> log/levels
  fgrep "equipment lost" syslog >> log/rentgone
  fgrep "usage" syslog >> log/usage
  fgrep "new player" syslog >> log/newplayers
  fgrep "SYSERR" syslog >> log/errors
  fgrep "(GC)" syslog >> log/godcmds
  fgrep "Bad PW" syslog >> log/badpws

  gzip syslog
  mv syslog.gz archive/syslog.$(date +%d%m%y).gz
  mv core.2 core.3
  mv core.1 core.2
  mv lib/core core.1
  chmod 660 core.1

  if [ -r .killscript ]; then
    DATE=`date`;
    echo "autoscript killed $DATE"  >>syslog
    rm .killscript
    exit
  fi

  if [ ! -r .fastboot ]; then
    sleep 60
  else
    rm .fastboot
    sleep 5
  fi

  while [ -r pause ]; do
    sleep 60
  done

done
