#!/bin/sh

PORT=4000
ulimit -c unlimited
FLAGS=''
export MALLOC_CHECK_=1
export BYLINS_HOME=$(pwd)
umask 002

KILL_TRIGGER=.killscript
CRASH_TRIGGER=.crash
PAUSE_FLAG=pause
FASTBOOT_FLAG=.fastboot

truncate syslog --size 0
truncate output --size 0

#############################################################################

while ( : ) do
  cd $BYLINS_HOME
  echo "$(pwd) is current directory now"
  DATE=`date`
  echo "autorun starting game $DATE" | tee -a syslog
  echo "statring bin/circle $FLAGS $PORT" | tee -a syslog

  ./circle $FLAGS $PORT 2>&1 | tee -a output 2>&1

  if [ -f circle.2 ]; then mv circle.2 circle.3; fi
  if [ -f circle.1 ]; then mv circle.1 circle.2; fi
  if [ -f core ]; then mv lib/core circle.1; fi

  if [ -f circle.1 ]; then gdb circle circle.1 -x gdbrun --batch-silent >> log.core; fi
  if [ -f log.core.2 ]; then mv log.core.2 log.core.3; fi
  if [ -f log.core.1 ]; then mv log.core.1 log.core.2; fi
  if [ -f log.core ]; then mv log.core log.core.1; fi

  if [ -f syslog ]; then tail -1000 syslog > log.crash; fi
  if [ -f log.crash.2 ]; then mv log.crash.2 log.crash.3; fi
  if [ -f log.crash.1 ]; then mv log.crash.1 log.crash.2; fi
  if [ -f log.crash ]; then mv log.crash log.crash.1; fi

  ./makelog

  cd $BYLINS_HOME
			
  # Докер должен не перезапускать скрипт, если он завершился с нулевым результатом: опция --restart=on-failure 
  if [ -r ${KILL_TRIGGER} ]; then
    rm -fv ${KILL_TRIGGER}
    if [ -r ${CRASH_TRIGGER} ]; then
      rm -fv ${CRASH_TRIGGER}
    fi
    exit 0
  fi

  if [ ! -r ${PAUSE_FLAG} ]; then
    if [ -r ${FASTBOOT_FLAG} ]; then
      rm -fv ${FASTBOOT_FLAG}
      sleep 5
    else
      sleep 59
    fi
  else
    while [ -r ${PAUSE_FLAG} ]; do
      sleep 60
    done
  fi
done
