# Object #153
vnum: 153
names:
  aliases: пузатый_бочонок бочонок_пузатый
  nominative: пузатый_бочонок
  genitive: пузатого_бочонка
  dative: пузатому_бочонку
  accusative: пузатый_бочонок
  instrumental: пузатым_бочонком
  prepositional: пузатом_бочонке
short_desc: Небольшой бочонок с синей отметкой стоит на земле.
type: kLiquidContainer
wear_flags:
- kTake
material: 9
values:
- '75'
- '75'
- '18'
- '0'
weight: 80
cost: 3100
rent_off: 50
rent_on: 50
spec_param: 145
max_durability: 400
cur_durability: 400
timer: 30150
spell: 0
level: 0
sex: kMale
extra_descriptions:
- keywords: бочонок
  description: "\r\n"
max_in_world: 9999
triggers:
- 58104
