# Object #155
vnum: 155
names:
  aliases: кости бабки костяные
  nominative: костяные бабки
  genitive: костяных бабок
  dative: костяным бабкам
  accusative: костяные бабки
  instrumental: костяными бабками
  prepositional: костяных бабках
short_desc: Костяные бабки заманчиво притягивают Вас.
type: kTrap
wear_flags:
- kTake
- kHold
material: 13
values:
- '0'
- '0'
- '0'
- '0'
weight: 1
cost: 10
rent_off: 100
rent_on: 20
spec_param: 0
max_durability: 30
cur_durability: 30
timer: 500000
spell: -1
level: 0
sex: kPoly
max_in_world: 100000
triggers:
- 26055
