# Object #198
vnum: 198
names:
  aliases: магический браслет
  nominative: магический браслет
  genitive: магического браслета
  dative: магическому браслету
  accusative: магический браслет
  instrumental: магическим браслетом
  prepositional: магическом браслете
short_desc: Магический браслет лежит здесь.
type: kWorm
wear_flags:
- kTake
- kFinger
- kWrist
material: 16
values:
- '0'
- '0'
- '0'
- '0'
weight: 1
cost: 1
rent_off: 0
rent_on: 1
spec_param: 0
max_durability: 500
cur_durability: 500
timer: 30
spell: -1
level: 0
sex: kNeutral
applies:
- location: 1
  modifier: 30
triggers:
- 166
