# Room #4056
vnum: 4056
zone: 40
name: Гостиный двор
description: "___После дороги дальней, посидев за чарой зелена вина, да погутарив со\r\nдрузьями - товарищами о подвигах ратных да о девицах красных, нет ничего\r\nкраше, чем растянуться на перине, на пуховой да забыться сном богатырским.\r\nВот и облюбовали себе сей двор послы дальнеземные, да богатыри заезжие для \r\nотдохновения от забот и сует мирских.\r\n&GСовсем малых, да необученных так и тянет &Yвойти &Gв &Yшколу&G.&n\r\n"
flags:
- kIndoors
- kPeaceful
- kForMages
- kForSorcerers
- kForThieves
- kForWarriors
- kForAssasines
- kForGuards
- kForPaladines
- kForRangers
- kForPoly
- kForMono
- kNohorse
sector: kCity
exits:
- direction: east
  exit_flags: 0
  key: -1
  to_room: 4014
  lock_complexity: 0
triggers:
- 9118
