# Room #4058
vnum: 4058
zone: 40
name: Большая яма
description: "   Большая яма, вырытая в глиняном пласту и выложенная снизу тесом окружает\r\nвас. Выбраться отсюда невозможно, а если добавить к этому решетку, закрывающую\r\nединственный лаз из ямы, то начинаешь понимать что отсюда могут только\r\nвыпустить. Похоже это местная темница. Вверху, за решеткой, вы видите вашего стража,\r\nкоторый сильно ругается, припоминает всех ваших родственников до десятого колена.\r\nВы поникли духом, и хныкая, хотите просить прощения: \"Простите меня дурака\".\r\n"
flags:
- kPeaceful
- kNoMagic
- kNoTeleportIn
- kNoTeleportOut
- kNohorse
- kNoWeather
sector: kCity
triggers:
- 4004
