# Room #100
vnum: 100
zone: 1
name: Тронный зал.
description: "   Величественные мраморные колонны уходят ввысь, подпирая самое небо.  На стенах,\r\nотделанных редчайшими сортами мрамора красуются барельефы, изображающие бытие\r\nобитателей замка - охоту на Жар-Птицу, воскрешение Змея Горыныча, зверски\r\nизрубленного Ильей Муромцем после очередной попойки, пленение Змея Тугарина и\r\nмногое другое. В центре зала - огромный дубовый стол, покрытый скатертью-самобранкой.\r\n"
flags:
- kIndoors
- kNoMagic
- kArena
- kNoTeleportOut
- kNoWeather
- kNoRelocateIn
sector: kInside
exits:
- direction: north
  exit_flags: 0
  key: 0
  to_room: 185
  lock_complexity: 0
- direction: east
  exit_flags: 0
  key: 0
  to_room: 1100
  lock_complexity: 0
- direction: south
  exit_flags: 0
  key: 0
  to_room: 184
  lock_complexity: 0
- direction: down
  exit_flags: 0
  key: 0
  to_room: 104
  lock_complexity: 0
triggers:
- 100
- 198
