# Room #101
vnum: 101
zone: 1
name: Темница
description: "   Угрюмые мрачные многометровые стены окружают тебя со всех сторон. У самого\r\nпотолка кровью начертаны какие-то знаки. Приглядевшись повнимательнее, ты смог\r\nразобрать старинные буквы:\r\n___&rОСТАВЬ НАДЕЖДУ, ВСЯК СЮДА ПОПАВШИЙ.&n\r\n___&rЛюбые Пк действия в аду запрещены, наказуемы вплоть до фриза.\r\n\r\n___&RПОТЕРЯ СВЯЗИ ПРИ ПРОВЕРКЕ НА МУЛЬТИНГ РАВНОСИЛЬНА ПРИЗНАНИЮ СВОЕЙ ВИНЫ!&n\r\n____\r\n"
flags:
- kNoEntryMob
- kIndoors
- kPeaceful
- kSoundproof
- kNoTrack
- kNoMagic
- kNoTeleportIn
- kNoSummonOut
- kNoTeleportOut
- kNoWeather
- kNoRelocateIn
- kNoItem
sector: kCity
exits:
- direction: up
  description: Решетка
  keywords: решетка|решетку
  exit_flags: 9
  key: 0
  to_room: 104
  lock_complexity: 0
triggers:
- 100
- 198
