# Room #102
vnum: 102
zone: 1
name: Странная комната
description: "   Пить меньше надо..\r\n"
flags:
- kIndoors
- kPeaceful
- kNoMagic
- kNoTeleportIn
- kNoSummonOut
- kNoTeleportOut
- kNoWeather
- kNoRelocateIn
sector: kSecret
triggers:
- 198
