# Room #103
vnum: 103
zone: 1
name: Комната для незарегистрированных игроков, играющих через прокси.
description: "   Еще одна забава нынешних правителей. По словам очевидцев - есть у них\r\nкомната, все выходы из которой зачарованы - куда бы ты ни пошел - обязательно\r\nвозвращаешься сюда же. Немало народу полегло здесь, пока смилостившиеся хозяева\r\nне снизойдут до путника и не разорвут этот заколдованный круг.\r\n___&RЕсли Вы здесь оказались - значит в игре уже есть персонаж с Вашего IP!&n\r\nЕсли Вы играете из клуба, сети, используете прокси, а так же не \"мультите\",\r\nто можете просить Богов зарегистрировать Вас.\r\nПри этом полезно будет указать кто именно и почему находится с Вами с 1го адреса,\r\nЭто значительно ускорит регистрацию.\r\n___&WПросто так никто никого не регистрирует! Приятного времяпровождения!&n\r\n"
flags:
- kPeaceful
- kNoMagic
- kNoTeleportIn
- kNoSummonOut
- kNoTeleportOut
- kNoWeather
- kNoRelocateIn
- kNoItem
sector: kCity
exits:
- direction: north
  exit_flags: 0
  key: -1
  to_room: 103
  lock_complexity: 0
- direction: east
  exit_flags: 0
  key: -1
  to_room: 103
  lock_complexity: 0
- direction: south
  exit_flags: 0
  key: -1
  to_room: 103
  lock_complexity: 0
- direction: west
  exit_flags: 0
  key: -1
  to_room: 103
  lock_complexity: 0
- direction: up
  exit_flags: 0
  key: -1
  to_room: 103
  lock_complexity: 0
- direction: down
  exit_flags: 0
  key: -1
  to_room: 103
  lock_complexity: 0
triggers:
- 100
- 198
