# Room #104
vnum: 104
zone: 1
name: Гостиная палата.
description: "   Длинная и просторная зала, в которой правители принимают простой люд,\r\nвыслушивают жалобы, принимают челобитные, а порой вершат скорый суд над\r\nзлодеями. В центре зала заметен отделанный крепким деревом люк, который по \r\nсловам ведет в глубокие княжеские темницы под замком.\r\n"
flags:
- kIndoors
- kPeaceful
- kNoMagic
- kArena
- kNoSummonOut
- kNoTeleportOut
- kNoWeather
- kNoRelocateIn
sector: kInside
exits:
- direction: north
  exit_flags: 0
  key: 0
  to_room: 0
  lock_complexity: 0
- direction: south
  description: Недоделанная комната
  exit_flags: 0
  key: 0
  to_room: 186
  lock_complexity: 0
- direction: up
  exit_flags: 0
  key: 0
  to_room: 100
  lock_complexity: 0
- direction: down
  exit_flags: 0
  key: 0
  to_room: 101
  lock_complexity: 0
triggers:
- 100
- 198
