# Room #105
vnum: 105
zone: 1
name: Темница для людей с неверными именами
description: "   Вы попали в комнату огромной высоты но очень маленькую по площади. Здесь нет\r\nничего интересного, кроме огромного камня в центре комнаты.\r\n"
flags:
- kNoEntryMob
- kIndoors
- kPeaceful
- kSoundproof
- kNoMagic
- kNoTeleportIn
- kNoSummonOut
- kNoTeleportOut
- kNohorse
- kNoWeather
sector: kInside
triggers:
- 100
- 198
