# Room #112
vnum: 112
zone: 1
name: Одиночная камера N7
description: "   Угрюмые мрачные многометровые стены окружают тебя со всех сторон. Комната \r\nмаленькая, с тусклым грязным окошком под потолком. Тяжелая кованная дверь\r\nзакрывает выход из комнаты. Недалеко слышны душераздирающие звуки пыток\r\nи допросов. Выберусь ли живой отсюда? - вот мысль постоянно пульсирующая\r\nв вашей голове.\r\n"
flags:
- kNoEntryMob
- kIndoors
- kPeaceful
- kSoundproof
- kNoMagic
- kNoSummonOut
- kNoTeleportOut
- kNoWeather
sector: kInside
triggers:
- 198
