# Room #116
vnum: 116
zone: 1
name: Комната темной красавицы
description: "   Вы вошли в маленькую комнату под самым небом, сюда могут входить тольео самые\r\nблизкие люди великой колдуньи Морганы. По полкам стояли сосуды с мазями, сухими\r\nягодами и разноцветными жидкостями. На тонких жердях, протянутых под потолком,\r\nвисели коренья, пучки высохших трав и цветов. Много места занимает очаг из\r\nкрасного кирпича, в очаге горят березовые дрова, заставляя бурно кипеть варево\r\nв котле, из которого выползает длинный змеевик.\r\n"
flags:
- kIndoors
- kPeaceful
- kNoMagic
- kNoSummonOut
- kNoWeather
sector: kInside
triggers:
- 198
