# Room #120
vnum: 120
zone: 1
name: Зал мертвых
description: "___Огромный зал, словно вырубленный в скале. Гладкие колонны взмывают ввысь,\r\nтеряясь в темноте. Кристаллики льда хрустят  под ногами, иногда взвиваясь\r\nвместе с поземкой аж до уровня груди. Дорожка из плотно пригнанных друг к другу\r\nплит приводит к небольшому возвышению, на котором стоит хрустальный трон.\r\nАбсолютное безмолвие с легким поскрипыванием льдинок заставляет Вас зябко\r\nкутаться в одежду и вжимать голову в плечи.\r\n"
flags:
- kNoMagic
sector: kInside
exits:
- direction: north
  description: "покои Морены\r\n"
  keywords: дверь|дверь
  exit_flags: 1
  key: 0
  to_room: 121
  lock_complexity: 0
triggers:
- 198
