# Room #121
vnum: 121
zone: 1
name: Покои Морены
description: "___Огромный будуар Хозяйки Мертвых. Только тут горит огонь в камине,\r\nдаря тепло хозяйке и гостям. Перед камином лежит шкура полярного барса.\r\nОгромная кровать в углу будуара, завалена шкурами песцов и черно-бурых лис.\r\nМантия, подбитая горностаем, небрежно брошена на спинку кресла, стоящего около\r\nволшебного зеркала в серебряной оправе.\r\n"
flags:
- kNoWeather
sector: kInside
exits:
- direction: east
  exit_flags: 0
  key: 0
  to_room: 0
  lock_complexity: 0
- direction: south
  description: "Зал Мертвых\r\n"
  keywords: дверь|дверь
  exit_flags: 1
  key: 0
  to_room: 120
  lock_complexity: 0
triggers:
- 198
