# Room #136
vnum: 136
zone: 1
name: '&Y__Прибежище Руевита&n'
description: "   Вы оказались в просторном светлом зале с очень высоким потолком. Залитый\r\nярким светом желтых шаров неизвестного происхождения и устройства, в центре\r\nзала стоит дубовый идол. Тишина и абсолютная неподвижность воздуха кажутся\r\nстранными и неестественными.  \r\n"
flags:
- kDarked
- kForPoly
- kArena
- kNoSummonOut
sector: kInside
exits:
- direction: east
  exit_flags: 0
  key: 0
  to_room: 0
  lock_complexity: 0
- direction: west
  exit_flags: 1
  key: 0
  to_room: 103
  lock_complexity: 0
- direction: up
  exit_flags: 1
  key: 0
  to_room: 100
  lock_complexity: 0
- direction: down
  exit_flags: 1
  key: 0
  to_room: 20962
  lock_complexity: 0
triggers:
- 1170
