# Room #184
vnum: 184
zone: 1
name: Комната наказаний.
description: "___Очень странная комната. Словно она делится на две части. В одной части на большой\r\nмраморной плите мелькают странные надписи, похожие на неправильные имена. А в другой\r\nкамни от жара светятся красным сиянием. В середине комнаты стоит доска,\r\nвыбитая в золотом слитке и именуемая доска потерянных судеб.\r\n"
flags:
- kIndoors
- kNoMagic
- kNoTeleportIn
- kArena
- kNoSummonOut
- kNoTeleportOut
- kNoRelocateIn
sector: kInside
exits:
- direction: north
  exit_flags: 0
  key: 0
  to_room: 100
  lock_complexity: 0
triggers:
- 198
