# Room #185
vnum: 185
zone: 1
name: Комната смертной доски
description: "___Большая мраморная комната. По углам стоят четыре белыx колонны, уходя высоко в потолок.\r\nПол весь покрыт плиткой с замысловатыми рисунками. Перед доской стоят четыре стула и маленький\r\nкруглый столик.\r\n"
flags:
- kIndoors
- kNoMagic
- kNoTeleportIn
- kArena
- kNoTeleportOut
- kNoWeather
- kNoRelocateIn
sector: kInside
exits:
- direction: south
  exit_flags: 0
  key: 0
  to_room: 100
  lock_complexity: 0
triggers:
- 198
