# Room #186
vnum: 186
zone: 1
name: Недоделанная комната
description: "Вы оказались в комнате, наполненной обломками творческих мыслей КОДЕРА.\r\n"
flags:
- kIndoors
- kPeaceful
- kNoMagic
- kNoTeleportIn
- kArena
- kNoSummonOut
- kNoTeleportOut
- kNoWeather
- kNoRelocateIn
sector: kInside
exits:
- direction: north
  exit_flags: 0
  key: 0
  to_room: 104
  lock_complexity: 0
- direction: east
  exit_flags: 0
  key: 0
  to_room: 0
  lock_complexity: 0
triggers:
- 100
- 198
