/**
\authors Created by Sventovit
\date 27.04.2022.
\brief Константы системы заклинаний.
*/

#ifndef BYLINS_SRC_GAME_MAGIC_SPELLS_CONSTANTS_H_
#define BYLINS_SRC_GAME_MAGIC_SPELLS_CONSTANTS_H_

#include "structs/structs.h"

const int kMaxMemoryCircle = 13;

enum ESpell : int {
	kUndefined = 0,
	kSpellArmor = 1,
	kSpellTeleport = 2,
	kSpellBless = 3,
	kSpellBlindness = 4,
	kSpellBurningHands = 5,
	kSpellCallLighting = 6,
	kSpellCharm = 7,
	kSpellChillTouch = 8,
	kSpellClone = 9,
	kSpellIceBolts = 10,
	kSpellControlWeather = 11,
	kSpellCreateFood = 12,
	kSpellCreateWater = 13,
	kSpellCureBlind = 14,
	kSpellCureCritic = 15,
	kSpellCureLight = 16,
	kSpellCurse = 17,
	kSpellDetectAlign = 18,
	kSpellDetectInvis = 19,
	kSpellDetectMagic = 20,
	kSpellDetectPoison = 21,
	kSpellDispelEvil = 22,
	kSpellEarthquake = 23,
	kSpellEnchantWeapon = 24,
	kSpellEnergyDrain = 25,
	kSpellFireball = 26,
	kSpellHarm = 27,
	kSpellHeal = 28,
	kSpellInvisible = 29,
	kSpellLightingBolt = 30,
	kSpellLocateObject = 31,
	kSpellMagicMissile = 32,
	kSpellPoison = 33,
	kSpellProtectFromEvil = 34,
	kSpellRemoveCurse = 35,
	kSpellSanctuary = 36,
	kSpellShockingGasp = 37,
	kSpellSleep = 38,
	kSpellStrength = 39,
	kSpellSummon = 40,
	kSpellPatronage = 41,
	kSpellWorldOfRecall = 42,
	kSpellRemovePoison = 43,
	kSpellSenseLife = 44,
	kSpellAnimateDead = 45,
	kSpellDispelGood = 46,
	kSpellGroupArmor = 47,
	kSpellGroupHeal = 48,
	kSpellGroupRecall = 49,
	kSpellInfravision = 50,
	kSpellWaterwalk = 51,
	kSpellCureSerious = 52,
	kSpellGroupStrength = 53,
	kSpellHold = 54,
	kSpellPowerHold = 55,
	kSpellMassHold = 56,
	kSpellFly = 57,
	kSpellBrokenChains = 58,
	kSpellNoflee = 59,
	kSpellCreateLight = 60,
	kSpellDarkness = 61,
	kSpellStoneSkin = 62,
	kSpellCloudly = 63,
	kSpellSllence = 64,
	kSpellLight = 65,
	kSpellChainLighting = 66,
	kSpellFireBlast = 67,
	kSpellGodsWrath = 68,
	kSpellWeaknes = 69,
	kSpellGroupInvisible = 70,
	kSpellShadowCloak = 71,
	kSpellAcid = 72,
	kSpellRepair = 73,
	kSpellEnlarge = 74,
	kSpellFear = 75,
	kSpellSacrifice = 76,
	kSpellWeb = 77,
	kSpellBlink = 78,
	kSpellRemoveHold = 79,
	kSpellCamouflage = 80,
	kSpellPowerBlindness = 81,
	kSpellMassBlindness = 82,
	kSpellPowerSilence = 83,
	kSpellExtraHits = 84,
	kSpellResurrection = 85,
	kSpellMagicShield = 86,
	kSpellForbidden = 87,
	kSpellMassSilence = 88,
	kSpellRemoveSilence = 89,
	kSpellDamageLight = 90,
	kSpellDamageSerious = 91,
	kSpellDamageCritic = 92,
	kSpellMassCurse = 93,
	kSpellArmageddon = 94,
	kSpellGroupFly = 95,
	kSpellGroupBless = 96,
	kSpellResfresh = 97,
	kSpellStunning = 98,
	kSpellHide = 99,
	kSpellSneak = 100,
	kSpellDrunked = 101,
	kSpellAbstinent = 102,
	kSpellFullFeed = 103,
	kSpellColdWind = 104,
	kSpellBattle = 105,
	kSpellHaemorrhage = 106,
	kSpellCourage = 107,
	kSpellWaterbreath = 108,
	kSpellSlowdown = 109,
	kSpellHaste = 110,
	kSpellMassSlow = 111,
	kSpellGroupHaste = 112,
	kSpellGodsShield = 113,
	kSpellFever = 114,
	kSpellCureFever = 115,
	kSpellAwareness = 116,
	kSpellReligion = 117,
	kSpellAirShield = 118,
	kSpellPortal = 119,
	kSpellDispellMagic = 120,
	kSpellSummonKeeper = 121,
	kSpellFastRegeneration = 122,
	kSpellCreateWeapon = 123,
	kSpellFireShield = 124,
	kSpellRelocate = 125,
	kSpellSummonFirekeeper = 126,
	kSpellIceShield = 127,
	kSpellIceStorm = 128,
	kSpellLessening = 129,
	kSpellShineFlash = 130,
	kSpellMadness = 131,
	kSpellGroupMagicGlass = 132,
	kSpellCloudOfArrows = 133,
	kSpellVacuum = 134,
	kSpellMeteorStorm = 135,
	kSpellStoneHands = 136,
	kSpellMindless = 137,
	kSpellPrismaticAura = 138,
	kSpellEviless = 139,
	kSpellAirAura = 140,
	kSpellFireAura = 141,
	kSpellIceAura = 142,
	kSpellShock = 143,
	kSpellMagicGlass = 144,
	kSpellGroupSanctuary = 145,
	kSpellGroupPrismaticAura = 146,
	kSpellDeafness = 147,
	kSpellPowerDeafness = 148,
	kSpellRemoveDeafness = 149,
	kSpellMassDeafness = 150,
	kSpellDustStorm = 151,
	kSpellEarthfall = 152,
	kSpellSonicWave = 153,
	kSpellHolystrike = 154,
	kSpellSumonAngel = 155,
	kSpellMassFear = 156,
	kSpellFascination = 157,
	kSpellCrying = 158,
	kSpellOblivion = 159,
	kSpellBurdenOfTime = 160,
	kSpellGroupRefresh = 161,
	kSpellPeaceful = 162,
	kSpellMagicBattle = 163,
	kSpellBerserk = 164,
	kSpellStoneBones = 165,
	kSpellRoomLight = 166,
	kSpellPoosinedFog = 167,
	kSpellThunderstorm = 168,
	kSpellLightWalk = 169,
	kSpellFailure = 170,
	kSpellClanPray = 171,
	kSpellGlitterDust = 172,
	kSpellScream = 173,
	kSpellCatGrace = 174,
	kSpellBullBody = 175,
	kSpellSnakeWisdom = 176,
	kSpellGimmicry = 177,
	kSpellWarcryOfChallenge = 178,
	kSpellWarcryOfMenace = 179,
	kSpellWarcryOfRage = 180,
	kSpellWarcryOfMadness = 181,
	kSpellWarcryOfThunder = 182,
	kSpellWarcryOfDefence = 183,
	kSpellWarcryOfBattle = 184,
	kSpellWarcryOfPower = 185,
	kSpellWarcryOfBless = 186,
	kSpellWarcryOfCourage = 187,
	kSpellRuneLabel = 188,
	kSpellAconitumPoison = 189,
	kSpellScopolaPoison = 190,
	kSpellBelenaPoison = 191,
	kSpellDaturaPoison = 192,
	kSpellTimerRestore = 193,
	kSpellLucky = 194,
	kSpellBandage = 195,
	kSpellNoBandage = 196,
	kSpellCapable = 197,
	kSpellStrangle = 198,
	kSpellRecallSpells = 199,
	kSpellHypnoticPattern = 200,
	kSpellSolobonus = 201,
	kSpellVampirism = 202,
	kSpellRestoration = 203,
	kSpellDeathAura = 204,
	kSpellRecovery = 205,
	kSpellMassRecovery = 206,
	kSpellAuraOfEvil = 207,
	kSpellMentalShadow = 208,
	kSpellBlackTentacles = 209,
	kSpellWhirlwind = 210,
	kSpellIndriksTeeth = 211,
	kSpellAcidArrow = 212,
	kSpellThunderStone = 213,
	kSpellClod = 214,
	kSpellExpedient = 215,
	kSpellSightOfDarkness = 216,
	kSpellGroupSincerity = 217,
	kSpellMagicalGaze = 218,
	kSpellAllSeeingEye = 219,
	kSpellEyeOfGods = 220,
	kSpellBreathingAtDepth = 221,
	kSpellGeneralRecovery = 222,
	kSpellCommonMeal = 223,
	kSpellStoneWall = 224,
	kSpellSnakeEyes = 225,
	kSpellEarthAura = 226,
	kSpellGroupProtectFromEvil = 227,
	kSpellArrowsFire = 228,
	kSpellArrowsWater = 229,
	kSpellArrowsEarth = 230,
	kSpellArrowsAir = 231,
	kSpellArrowsDeath = 232,
	kSpellPaladineInspiration = 233,
	kSpellDexterity = 234,
	kSpellGroupBlink = 235,
	kSpellGroupCloudly = 236,
	kSpellGroupAwareness = 237,
	kSpellWatctyOfExpirence = 238,
	kSpellWarcryOfLuck = 239,
	kSpellWarcryOfPhysdamage = 240,
	kSpellMassFailure = 241,
	kSpellSnare = 242,
	kSpellFireBreath = 243,
	kSpellGasBreath = 244,
	kSpellFrostBreath = 245,
	kSpellAcidBreath = 246,
	kSpellLightingBreath = 247,
	kSpellExpedientFail = 248,
	kSpellIdentify = 351,
	kSpellFullIdentify = 352,
	kSpellQUest = 353,
	kSpellFirst = kSpellArmor,
	kSpellLast = kSpellQUest	// Не забываем менять
};

const ESpell &operator++(ESpell &s);
std::ostream& operator<<(std::ostream & os, ESpell &s);

template<>
ESpell ITEM_BY_NAME<ESpell>(const std::string &name);
template<>
const std::string &NAME_BY_ITEM<ESpell>(const ESpell spell);

// текст заклинания для игроков, произнесенные заклинателями разных религий
struct CastPhraseList {
	std::string text_for_heathen;	// заклинание произнесенное язычником
	std::string text_for_christian;	// заклинание произнесенное христианиным
};

// возращает текст выводимый при спадении скила
std::string GetAffExpiredText(ESpell spell_id);
// возвращает фразу для заклинания согласно религии
// std::nullopt если соответсвующего заклинания в таблице нет
std::optional<CastPhraseList> GetCastPhrase(ESpell spell_id);

#endif //BYLINS_SRC_GAME_MAGIC_SPELLS_CONSTANTS_H_

// vim: ts=4 sw=4 tw=0 noet syntax=cpp :
