# Mob #106
vnum: 106
names:
  aliases: заплечных дел мастер
  nominative: заплечных дел мастер
  genitive: заплечных дел мастера
  dative: заплечных дел мастеру
  accusative: заплечных дел мастера
  instrumental: заплечных дел мастером
  prepositional: заплечных дел мастере
descriptions:
  short_desc: "Заплечных дел мастер стоит тут, держа в руке раскаленные клещи.\r\n"
  long_desc: "С мощным торсом, перекатывающимися мышцами на руках, этот палач много\r\nсил потратил, совершенствуя свое ремесло, и вот Вам и выпала доля\r\nпроверить это.\r\n"
action_flags:
- kSentinel
- kIsNpc
- kStayZone
- kNoSleep
- kNoTerrainAttack
affect_flags:
- kIsNpc
- kAggressive
- kHelper
alignment: 0
mob_type: E
stats:
  level: 11
  hitroll_penalty: 1
  armor: -10
  hp:
    dice_count: 30
    dice_size: 30
    bonus: 930
  damage:
    dice_count: 10
    dice_size: 10
    bonus: 0
gold:
  dice_count: 0
  dice_size: 0
  bonus: 0
experience: 0
position:
  default: kStanding
  start: kStanding
sex: kMale
attributes:
  strength: 30
  dexterity: 25
  constitution: 30
  charisma: 5
size: 70
mob_class: 102
race: 101
height: 198
weight: 200
skills:
- skill_id: 136
  value: 33
triggers:
- 199
enhanced:
  special_bitvector: a0b0c0d0e0f0
