# Mob #120
vnum: 120
names:
  aliases: розовый слоник
  nominative: '&Mрозовый слоник&n'
  genitive: розового слоника
  dative: розовому слонику
  accusative: розового слоника
  instrumental: розовым слоником
  prepositional: розовом слонике
descriptions:
  short_desc: "Розовый слоник парит над вами, радостно взмахивая ушами.\r\n"
  long_desc: "Товарищ, да ты обкурился уже. Это же лучший в мире розовый летающий слоник! Мдаа.. не узнаешь старого друга.\r\n"
action_flags:
- kIsNpc
- kAware
- kNoBlind
- kNoTrack
- kAirCreature
- kProgrammedLootGroup
affect_flags:
- kIsNpc
- kAggressive
- kHelper
- kProtected
- kNoMagicTerrainAttack
- kClone
alignment: 0
mob_type: E
stats:
  level: 4
  hitroll_penalty: 20
  armor: 0
  hp:
    dice_count: 1
    dice_size: 100
    bonus: 2
  damage:
    dice_count: 1
    dice_size: 1
    bonus: 0
gold:
  dice_count: 0
  dice_size: 0
  bonus: 0
experience: 0
position:
  default: kStanding
  start: kStanding
sex: kMale
attributes:
  strength: 35
size: 100
mob_class: 100
race: 100
height: 198
weight: 200
skills:
- skill_id: 136
  value: 12
triggers:
- 131
enhanced:
  bare_hand_attack: 14
  special_bitvector: '0'
