# Mob #168
vnum: 168
names:
  aliases: призрак кошмара
  nominative: призрак кошмара
  genitive: призрака кошмара
  dative: призраку кошмара
  accusative: призрака кошмара
  instrumental: призраком кошмара
  prepositional: призраке кошмара
descriptions:
  short_desc: "Призрак &Kкошмара&n &Rнаводит на Вас ужас.&n\r\n"
  long_desc: "Нечто полупрозрачное витает в воздухе пред Вами.\r\nСтоит только попытаться вглядеться в него получше, \r\nкак он принимает очертания самого ужасного Вашего &Kкошмара&n.\r\n"
action_flags:
- kSentinel
- kIsNpc
- kNoTerrainAttack
affect_flags:
- kSentinel
- kIsNpc
- kAggressive
- kHelper
alignment: 1
mob_type: E
stats:
  level: 35
  hitroll_penalty: 10
  armor: 0
  hp:
    dice_count: 1
    dice_size: 10000
    bonus: 1000
  damage:
    dice_count: 30
    dice_size: 1
    bonus: 10
gold:
  dice_count: 0
  dice_size: 0
  bonus: 0
experience: 0
position:
  default: kStanding
  start: kStanding
sex: kMale
size: 30
mob_class: 100
race: 100
height: 198
weight: 200
triggers:
- 167
enhanced:
  special_bitvector: a0
