# Mob #189
vnum: 189
names:
  aliases: страж сокровищницы богов
  nominative: страж сокровищницы богов
  genitive: стража сокровищницы богов
  dative: стражу сокровищницы богов
  accusative: стража сокровищницы богов
  instrumental: стражем сокровищницы богов
  prepositional: страже сокровищницы богов
descriptions:
  short_desc: "Высокий старик в белом одеянии пристально смотрит на вас.\r\n"
  long_desc: "Высокий старик в белом одеянии.\r\nГоды не сумели согнуть его статную фигуру бывшего воина.\r\n"
action_flags:
- kSentinel
- kIsNpc
- kNoSleep
- kNoTrack
- kFireCreature
- kWaterCreature
- kEarthCreature
- kProtected
- kNoTerrainAttack
affect_flags:
- kWimpy
- kNoFear
alignment: 600
mob_type: E
stats:
  level: 50
  hitroll_penalty: -30
  armor: -10
  hp:
    dice_count: 30
    dice_size: 50
    bonus: 20000
  damage:
    dice_count: 30
    dice_size: 127
    bonus: 50
gold:
  dice_count: 0
  dice_size: 0
  bonus: 0
experience: 0
position:
  default: kStanding
  start: kStanding
sex: kMale
attributes:
  strength: 50
  dexterity: 50
  intelligence: 50
  wisdom: 50
  constitution: 50
  charisma: 50
size: 30
mob_class: 100
race: 100
height: 198
weight: 200
skills:
- skill_id: 136
  value: 150
triggers:
- 1190
- 165
enhanced:
  like_work: 100
  special_bitvector: '0'
  spells:
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
  - 94
