# Mob #4002
vnum: 4002
names:
  aliases: сын старейшины
  nominative: сын старейшины
  genitive: сына старейшины
  dative: сыну старейшины
  accusative: сына старейшины
  instrumental: сыном старейшины
  prepositional: сыне старейшины
descriptions:
  short_desc: "Сын старейшины стоит здесь.\r\n"
  long_desc: "Стройный молодой парень.\r\n"
action_flags:
- kIsNpc
- kStayZone
- kNoSleep
- kNoBash
- kNoBlind
- kNoTerrainAttack
alignment: 600
mob_type: E
stats:
  level: 12
  hitroll_penalty: 17
  armor: 5
  hp:
    dice_count: 5
    dice_size: 10
    bonus: 200
  damage:
    dice_count: 2
    dice_size: 2
    bonus: 10
gold:
  dice_count: 0
  dice_size: 0
  bonus: 0
experience: 0
position:
  default: kStanding
  start: kStanding
sex: kMale
attributes:
  strength: 20
  dexterity: 20
  intelligence: 16
  wisdom: 16
  constitution: 18
  charisma: 15
size: 30
mob_class: 102
race: 101
height: 180
weight: 150
skills:
- skill_id: 136
  value: 36
triggers:
- 4003
enhanced:
  like_work: 50
  max_factor: 10
  special_bitvector: '0'
