# Mob #4012
vnum: 4012
names:
  aliases: охотник следопыт
  nominative: охотник
  genitive: охотника
  dative: охотнику
  accusative: охотника
  instrumental: охотником
  prepositional: охотнике
descriptions:
  short_desc: "Стройный молодой охотник-следопыт проходит здесь.\r\n"
  long_desc: "Стройный мужчина.\r\n"
action_flags:
- kIsNpc
- kStayZone
- kNoSleep
- kNoBash
- kNoBlind
- kNoTerrainAttack
alignment: 600
mob_type: E
stats:
  level: 10
  hitroll_penalty: 13
  armor: 0
  hp:
    dice_count: 10
    dice_size: 10
    bonus: 100
  damage:
    dice_count: 1
    dice_size: 5
    bonus: 3
gold:
  dice_count: 0
  dice_size: 0
  bonus: 0
experience: 0
position:
  default: kStanding
  start: kStanding
sex: kMale
attributes:
  strength: 20
  dexterity: 18
  intelligence: 15
  wisdom: 15
  constitution: 20
  charisma: 20
size: 30
mob_class: 100
race: 101
height: 180
weight: 150
skills:
- skill_id: 136
  value: 30
triggers:
- 4003
enhanced:
  max_factor: 10
  special_bitvector: '0'
