# Mob #4027
vnum: 4027
names:
  aliases: вдова мельника немолодая женщина
  nominative: вдова мельника
  genitive: вдовы мельника
  dative: вдове мельника
  accusative: вдову мельника
  instrumental: вдовой мельника
  prepositional: вдове мельника
descriptions:
  short_desc: "Немолодая женщина с открытым лицом с грустью смотрит на Вас.\r\n"
  long_desc: "   Немолодая уже женщина, тяжелая судьба которой наложила свой отпечаток\r\nна ее лицо.\r\n"
action_flags:
- kSentinel
- kIsNpc
- kNoSleep
- kNoBash
- kNoBlind
- kNoTerrainAttack
affect_flags:
- kNoSummoned
alignment: 600
mob_type: E
stats:
  level: 13
  hitroll_penalty: 12
  armor: 5
  hp:
    dice_count: 10
    dice_size: 10
    bonus: 250
  damage:
    dice_count: 2
    dice_size: 6
    bonus: 5
gold:
  dice_count: 0
  dice_size: 0
  bonus: 0
experience: 0
position:
  default: kStanding
  start: kStanding
sex: kFemale
attributes:
  strength: 16
  dexterity: 16
  intelligence: 20
  wisdom: 20
  constitution: 20
  charisma: 20
size: 30
mob_class: 102
race: 101
height: 150
weight: 60
skills:
- skill_id: 136
  value: 39
triggers:
- 4001
- 4003
enhanced:
  bare_hand_attack: 2
  special_bitvector: '0'
