#!/usr/bin/env python3
"""Refresh the AUTOGENERATED flag-table block inside convert_to_yaml.py.

By design convert_to_yaml.py keeps flat hard-coded Python lists for every
enum it cares about (ACTION_FLAGS, AFFECT_FLAGS, NPC_FLAGS, EXTRA_FLAGS,
NO_FLAGS, ANTI_FLAGS, WEAR_FLAGS, ROOM_FLAGS, WEAPON_AFFECT_FLAGS,
OBJ_TYPES, SECTORS, POSITIONS, GENDERS). This script reads the
authoritative C++ enums and rewrites that block in-place so the names
never drift. Run after editing any of those enums.

Usage:
    python3 tools/converter/regenerate_flag_tables.py            # rewrite
    python3 tools/converter/regenerate_flag_tables.py --check    # CI mode

The C++ parsing helpers below understand the Bylins planar packing:

    kFoo  = 1u << N            -> plane 0
    kBar  = kIntOne   | (1<<N) -> plane 1
    kBaz  = kIntTwo   | (1<<N) -> plane 2
    kQux  = kIntThree | (1<<N) -> plane 3

bit_index = plane * 30 + N
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]

ENT = REPO_ROOT / 'src/engine/entities/entities_constants.h'
AFF = REPO_ROOT / 'src/gameplay/affects/affect_contants.h'
CST = REPO_ROOT / 'src/gameplay/core/constants.cpp'
AFC = REPO_ROOT / 'src/gameplay/affects/affect_contants.cpp'
TARGET = REPO_ROOT / 'tools/converter/convert_to_yaml.py'

# ---------------------------------------------------------------------------
# C++ parsing primitives
# ---------------------------------------------------------------------------

PLANE_MARKER = {
    "kIntOne":   1 << 30,
    "kIntTwo":   2 << 30,
    "kIntThree": 3 << 30,
}


def _strip_comments(text: str) -> str:
    """Remove /* ... */ and // ... \\n comments from C++ source.

    Done before tokenization, because line comments often contain commas
    (Russian descriptions) which would otherwise corrupt the comma-split
    entry parser.
    """
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
    text = re.sub(r"//[^\n]*", "", text)
    return text


def _evaluate(expr: str) -> int:
    """Evaluate a C++ literal/operator expression on integers."""
    expr = expr.strip().rstrip(",")
    expr = expr.replace("u<<", "<<").replace("U<<", "<<")
    expr = re.sub(r"\b(\d+)[uU]\b", r"\1", expr)  # 1u<<5 -> 1<<5
    return int(eval(expr, {"__builtins__": None}, dict(PLANE_MARKER)))


def _extract_body(text: str, enum_name: str) -> str:
    pat = re.compile(
        rf"enum\s+(?:class\s+)?{re.escape(enum_name)}\b[^{{]*\{{(?P<body>.*?)\}}",
        re.DOTALL,
    )
    m = pat.search(text)
    if not m:
        raise ValueError(f"enum {enum_name} not found")
    return m.group("body")


def parse_flag_enum(header_path, enum_name):
    """Return {bit_index: enum_name} for a Bylins flag enum.

    Entries without ``= <expr>`` are skipped (we only handle explicit
    bit-index assignments — that's how every flag enum in the project is
    written).
    """
    text = Path(header_path).read_text(encoding="koi8-r", errors="replace")
    body = _strip_comments(_extract_body(text, enum_name))

    out = {}
    for raw in body.split(","):
        line = raw.strip()
        if not line:
            continue
        m = re.match(r"\s*([A-Za-z_]\w*)\s*=\s*(.+)$", line, re.DOTALL)
        if not m:
            continue
        name, expr = m.group(1), m.group(2)
        try:
            value = _evaluate(expr)
        except Exception:
            continue
        if value <= 0:
            continue
        plane = value >> 30
        bit_in_plane_mask = value & ((1 << 30) - 1)
        if bit_in_plane_mask == 0 or (bit_in_plane_mask & (bit_in_plane_mask - 1)) != 0:
            continue
        bit_in_plane = bit_in_plane_mask.bit_length() - 1
        bit_index = plane * 30 + bit_in_plane
        out.setdefault(bit_index, name)
    return out


def parse_flag_enum_as_list(header_path, enum_name, max_bit_index=120):
    """Return a dense list[bit_index] -> enum name.

    Gaps in the enum become ``UNUSED_<idx>`` so the result feeds straight
    into convert_to_yaml.py's helpers.
    """
    table = parse_flag_enum(header_path, enum_name)
    if not table:
        return []
    if max_bit_index <= 0:
        max_bit_index = max(table) + 1
    return [table.get(i, f"UNUSED_{i}") for i in range(max_bit_index)]


def parse_value_enum(header_path, enum_name):
    """Return {value: name} for an ordinary (non-bitfield) C++ enum.

    Entries without ``= <expr>`` get previous-value+1, matching C++.
    """
    text = Path(header_path).read_text(encoding="koi8-r", errors="replace")
    body = _strip_comments(_extract_body(text, enum_name))

    out = {}
    next_value = 0
    for raw in body.split(","):
        line = raw.strip()
        if not line:
            continue
        m = re.match(r"\s*([A-Za-z_]\w*)\s*(?:=\s*(.+))?$", line, re.DOTALL)
        if not m:
            continue
        name, expr = m.group(1), m.group(2)
        if expr is not None:
            try:
                value = _evaluate(expr)
            except Exception:
                continue
        else:
            value = next_value
        out.setdefault(value, name)
        next_value = value + 1
    return out


def parse_str_array(header_path, array_name):
    """Return raw list of string literals from a const-char array."""
    text = Path(header_path).read_text(encoding="koi8-r", errors="replace")
    pat = re.compile(
        rf"\bconst\s+char\s*\*\s*{re.escape(array_name)}\s*\[\s*\]\s*=\s*\{{(?P<body>.*?)\}}",
        re.DOTALL,
    )
    m = pat.search(text)
    if not m:
        raise ValueError(f"array {array_name} not found in {header_path}")
    body = _strip_comments(m.group("body"))
    return list(re.findall(r'"((?:[^"\\]|\\.)*)"', body))


def parse_ui_bits_table(header_path, array_name, plane_size=30):
    """Map bit_index -> UI label from a ``const char *foo[]`` bits table.

    The Bylins convention is:
        - 30 entries per plane (positions 0..29 within the plane).
        - ``"\\n"`` entries separate planes.
        - bit_index = plane_no * 30 + position_in_plane.

    Sentinels and gaps are skipped (returned dict only contains real names).
    """
    out = {}
    plane = 0
    pos = 0
    for s in parse_str_array(header_path, array_name):
        if s == "\\n" or s == "\n":
            plane += 1
            pos = 0
            continue
        out[plane * plane_size + pos] = s
        pos += 1
    return out


# ---------------------------------------------------------------------------
# Block generator
# ---------------------------------------------------------------------------

BEGIN = '# === BEGIN AUTOGENERATED FLAG TABLES ==='
END = '# === END AUTOGENERATED FLAG TABLES ==='


def _format_list(name: str, items, *, comment: str) -> str:
    out = [f"# {comment}"]
    out.append("# AUTOGENERATED — `python3 tools/converter/regenerate_flag_tables.py` to refresh.")
    out.append(f"{name} = [")
    cur = '    '
    for v in items:
        token = repr(v) + ','
        if len(cur) + len(token) + 1 > 100:
            out.append(cur.rstrip())
            cur = '    '
        cur += token + ' '
    if cur.strip():
        out.append(cur.rstrip())
    out.append(']')
    out.append('')
    return '\n'.join(out)


def _format_value_list(name: str, table: dict, *, comment: str) -> str:
    max_v = max(table) + 1 if table else 0
    items = [table.get(i) for i in range(max_v)]
    return _format_list(name, items, comment=comment)


def _ui_table_to_list(table: dict[int, str], length: int) -> list[str]:
    """Project a sparse {bit_index -> ui_name} dict onto a flat list of
    `length` slots; absent slots become empty strings."""
    return [table.get(i, '') for i in range(length)]


def _format_ui_list(name: str, items: list[str], *, comment: str) -> str:
    return _format_list(name, items, comment=comment)


# Bits-array sources matching each enum table. None -> no UI labels exist
# in the codebase; the dictionary will be emitted without per-key comments.
UI_TABLES = {
    'ACTION_FLAGS':        (CST, 'action_bits'),
    'AFFECT_FLAGS':        (AFC, 'affected_bits'),
    'EXTRA_FLAGS':         (CST, 'extra_bits'),
    'NO_FLAGS':            (CST, 'no_bits'),
    'ANTI_FLAGS':          (CST, 'anti_bits'),
    'WEAR_FLAGS':          (CST, 'wear_bits'),
    'ROOM_FLAGS':          (CST, 'room_bits'),
    'WEAPON_AFFECT_FLAGS': (CST, 'weapon_affects'),
    # Value enums: position == value, so a flat array maps directly.
    'OBJ_TYPES':           (CST, 'item_types'),
    'SECTORS':             (CST, 'sector_types'),
    'POSITIONS':           (CST, 'position_types'),
    'GENDERS':             (CST, 'genders'),
}


def build_block() -> str:
    # Generate full 120-bit (4 planes × 30 bits) tables, including UNUSED_NN
    # placeholders for unnamed bits. Loader-side dictionaries must include them
    # too — otherwise legacy worlds with bits set in unnamed positions lose
    # those bits on round-trip through YAML (caught by checksum diffs).
    #
    # Each enum table is paired with a *_UI_LABELS list that mirrors it 1:1
    # in length. Empty string means "no UI label defined in source" — the
    # corresponding YAML dictionary entry is then emitted without a comment.
    flag_specs = [
        ('ACTION_FLAGS',         ENT, 'EMobFlag',
         'Mob action flags / EMobFlag (mob_proto.char_specials.saved.act).'),
        ('AFFECT_FLAGS',         AFF, 'EAffect',
         'Mob affect flags / EAffect (mob_proto.char_specials.saved.affected_by).'),
        ('NPC_FLAGS',            ENT, 'ENpcFlag',
         'Mob NPC flags / ENpcFlag (mob_proto.mob_specials.npc_flags).'),
        ('EXTRA_FLAGS',          ENT, 'EObjFlag',
         'Object extra flags / EObjFlag.'),
        ('NO_FLAGS',             ENT, 'ENoFlag',
         'Object NO_x flags / ENoFlag.'),
        ('ANTI_FLAGS',           ENT, 'EAntiFlag',
         'Object ANTI_x flags / EAntiFlag.'),
        ('WEAR_FLAGS',           ENT, 'EWearFlag',
         'Object wear flags / EWearFlag.'),
        ('ROOM_FLAGS',           ENT, 'ERoomFlag',
         'Room flags / ERoomFlag.'),
        ('WEAPON_AFFECT_FLAGS',  AFF, 'EWeaponAffect',
         'Weapon-affect flags / EWeaponAffect (object affect_flags).'),
    ]
    value_specs = [
        ('OBJ_TYPES', ENT, 'EObjType',  'Object types / EObjType (None for gaps).'),
        ('SECTORS',   ENT, 'ESector',   'Sector types / ESector (None for gaps).'),
        ('POSITIONS', ENT, 'EPosition', 'Mob positions / EPosition.'),
        ('GENDERS',   ENT, 'EGender',   'Genders / EGender.'),
    ]

    parts = [
        BEGIN,
        '# Source of truth: src/engine/entities/entities_constants.h and',
        '# src/gameplay/affects/affect_contants.h. To refresh after enum edits,',
        '# run: python3 tools/converter/regenerate_flag_tables.py',
        '#',
        '# Lists span the full 120-bit range (4 planes × 30 bits) so unnamed',
        '# legacy bits round-trip cleanly via UNUSED_NN placeholders.',
        '#',
        '# Each FLAGS list is followed by a parallel <NAME>_UI_LABELS list (or',
        '# left empty when no bits[] table exists in C++ source). Convert-time',
        '# dictionary writers attach those labels as YAML EOL comments so',
        '# builders can read kSentinel: 1  # !ходит at a glance.',
        '',
    ]

    def kw_for(name: str):
        max_bit = 30 if name == 'WEAR_FLAGS' else 120
        return max_bit

    for name, header, enum_name, comment in flag_specs:
        items = parse_flag_enum_as_list(header, enum_name,
                                        max_bit_index=kw_for(name))
        parts.append(_format_list(name, items, comment=comment))
        if name in UI_TABLES:
            ui_path, ui_array = UI_TABLES[name]
            ui = parse_ui_bits_table(ui_path, ui_array)
            parts.append(_format_ui_list(
                f'{name}_UI_LABELS',
                _ui_table_to_list(ui, len(items)),
                comment=f'UI labels for {name} (from {ui_path.name}::{ui_array}[]).'))
        else:
            parts.append(f'{name}_UI_LABELS = [None] * len({name})\n')

    for name, header, enum_name, comment in value_specs:
        table = parse_value_enum(header, enum_name)
        max_v = max(table) + 1 if table else 0
        parts.append(_format_value_list(name, table, comment=comment))
        if name in UI_TABLES:
            ui_path, ui_array = UI_TABLES[name]
            # For value enums, the bits[] array is a flat list keyed by value
            # (not bit position). Skip plane separators and use the running
            # index directly.
            raw = parse_str_array(ui_path, ui_array)
            flat = [s for s in raw if s not in ('\\n', '\n')]
            ui_list = [flat[i] if i < len(flat) else '' for i in range(max_v)]
            parts.append(_format_ui_list(
                f'{name}_UI_LABELS', ui_list,
                comment=f'UI labels for {name} (from {ui_path.name}::{ui_array}[]).'))
        else:
            parts.append(f'{name}_UI_LABELS = [None] * len({name})\n')

    parts.append(END)
    return '\n'.join(parts)


def splice(text: str, new_block: str) -> str:
    lines = text.splitlines()
    try:
        b = next(i for i, l in enumerate(lines) if l.strip() == BEGIN)
        e = next(i for i, l in enumerate(lines) if l.strip() == END)
    except StopIteration:
        raise SystemExit(f"ERROR: BEGIN/END markers not found in {TARGET}")
    new_lines = lines[:b] + new_block.splitlines() + lines[e + 1:]
    return '\n'.join(new_lines) + ('\n' if text.endswith('\n') else '')


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--check', action='store_true',
                    help='Exit non-zero if convert_to_yaml.py is out of sync (CI mode).')
    args = ap.parse_args()

    block = build_block()
    text = TARGET.read_text(encoding='utf-8')
    expected = splice(text, block)

    if expected == text:
        print('convert_to_yaml.py: flag tables already up to date.')
        return 0

    if args.check:
        print('ERROR: convert_to_yaml.py is out of sync with C++ enums.', file=sys.stderr)
        print('Run: python3 tools/converter/regenerate_flag_tables.py', file=sys.stderr)
        return 1

    TARGET.write_text(expected, encoding='utf-8')
    print(f'convert_to_yaml.py: rewrote AUTOGENERATED flag tables ({len(block.splitlines())} lines).')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
