#!/usr/bin/env python3
"""Refresh the AUTOGENERATED flag-table block inside convert_to_yaml.py.

By design convert_to_yaml.py keeps flat hard-coded Python lists for every
enum it cares about (ACTION_FLAGS, AFFECT_FLAGS, NPC_FLAGS, EXTRA_FLAGS,
NO_FLAGS, ANTI_FLAGS, WEAR_FLAGS, ROOM_FLAGS, WEAPON_AFFECT_FLAGS,
OBJ_TYPES, SECTORS, POSITIONS, GENDERS). This script reads the
authoritative C++ enums and rewrites that block in-place so the names
never drift. Run after editing any of those enums.

Usage:
    python3 tools/converter/regenerate_flag_tables.py            # rewrite
    python3 tools/converter/regenerate_flag_tables.py --check    # CI mode
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT))

from tools.converter.cxx_enum import parse_flag_enum_as_list, parse_value_enum  # noqa: E402

ENT = REPO_ROOT / 'src/engine/entities/entities_constants.h'
AFF = REPO_ROOT / 'src/gameplay/affects/affect_contants.h'
TARGET = REPO_ROOT / 'tools/converter/convert_to_yaml.py'

BEGIN = '# === BEGIN AUTOGENERATED FLAG TABLES ==='
END = '# === END AUTOGENERATED FLAG TABLES ==='


def _format_list(name: str, items, *, comment: str) -> str:
    out = [f"# {comment}"]
    out.append("# AUTOGENERATED — `python3 tools/converter/regenerate_flag_tables.py` to refresh.")
    out.append(f"{name} = [")
    cur = '    '
    for v in items:
        token = repr(v) + ','
        if len(cur) + len(token) + 1 > 100:
            out.append(cur.rstrip())
            cur = '    '
        cur += token + ' '
    if cur.strip():
        out.append(cur.rstrip())
    out.append(']')
    out.append('')
    return '\n'.join(out)


def _format_value_list(name: str, table: dict, *, comment: str) -> str:
    max_v = max(table) + 1 if table else 0
    items = [table.get(i) for i in range(max_v)]
    return _format_list(name, items, comment=comment)


def build_block() -> str:
    # Generate full 120-bit (4 planes × 30 bits) tables, including UNUSED_NN
    # placeholders for unnamed bits. Loader-side dictionaries must include them
    # too — otherwise legacy worlds with bits set in unnamed positions lose
    # those bits on round-trip through YAML (caught by checksum diffs).
    parts = [
        BEGIN,
        '# Source of truth: src/engine/entities/entities_constants.h and',
        '# src/gameplay/affects/affect_contants.h. To refresh after enum edits,',
        '# run: python3 tools/converter/regenerate_flag_tables.py',
        '#',
        '# Lists span the full 120-bit range (4 planes × 30 bits) so unnamed',
        '# legacy bits round-trip cleanly via UNUSED_NN placeholders.',
        '',
        _format_list('ACTION_FLAGS',
                     parse_flag_enum_as_list(ENT, 'EMobFlag'),
                     comment='Mob action flags / EMobFlag (mob_proto.char_specials.saved.act).'),
        _format_list('AFFECT_FLAGS',
                     parse_flag_enum_as_list(AFF, 'EAffect'),
                     comment='Mob affect flags / EAffect (mob_proto.char_specials.saved.affected_by).'),
        _format_list('NPC_FLAGS',
                     parse_flag_enum_as_list(ENT, 'ENpcFlag'),
                     comment='Mob NPC flags / ENpcFlag (mob_proto.mob_specials.npc_flags).'),
        _format_list('EXTRA_FLAGS',
                     parse_flag_enum_as_list(ENT, 'EObjFlag'),
                     comment='Object extra flags / EObjFlag.'),
        _format_list('NO_FLAGS',
                     parse_flag_enum_as_list(ENT, 'ENoFlag'),
                     comment='Object NO_x flags / ENoFlag.'),
        _format_list('ANTI_FLAGS',
                     parse_flag_enum_as_list(ENT, 'EAntiFlag'),
                     comment='Object ANTI_x flags / EAntiFlag.'),
        _format_list('WEAR_FLAGS',
                     parse_flag_enum_as_list(ENT, 'EWearFlag', max_bit_index=30),
                     comment='Object wear flags / EWearFlag.'),
        _format_list('ROOM_FLAGS',
                     parse_flag_enum_as_list(ENT, 'ERoomFlag'),
                     comment='Room flags / ERoomFlag.'),
        _format_list('WEAPON_AFFECT_FLAGS',
                     parse_flag_enum_as_list(AFF, 'EWeaponAffect'),
                     comment='Weapon-affect flags / EWeaponAffect (object affect_flags).'),
        _format_value_list('OBJ_TYPES',
                            parse_value_enum(ENT, 'EObjType'),
                            comment='Object types / EObjType (None for gaps).'),
        _format_value_list('SECTORS',
                            parse_value_enum(ENT, 'ESector'),
                            comment='Sector types / ESector (None for gaps).'),
        _format_value_list('POSITIONS',
                            parse_value_enum(ENT, 'EPosition'),
                            comment='Mob positions / EPosition.'),
        _format_value_list('GENDERS',
                            parse_value_enum(ENT, 'EGender'),
                            comment='Genders / EGender.'),
        END,
    ]
    return '\n'.join(parts)


def splice(text: str, new_block: str) -> str:
    lines = text.splitlines()
    try:
        b = next(i for i, l in enumerate(lines) if l.strip() == BEGIN)
        e = next(i for i, l in enumerate(lines) if l.strip() == END)
    except StopIteration:
        raise SystemExit(f"ERROR: BEGIN/END markers not found in {TARGET}")
    new_lines = lines[:b] + new_block.splitlines() + lines[e + 1:]
    return '\n'.join(new_lines) + ('\n' if text.endswith('\n') else '')


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--check', action='store_true',
                    help='Exit non-zero if convert_to_yaml.py is out of sync (CI mode).')
    args = ap.parse_args()

    block = build_block()
    text = TARGET.read_text(encoding='utf-8')
    expected = splice(text, block)

    if expected == text:
        print('convert_to_yaml.py: flag tables already up to date.')
        return 0

    if args.check:
        print('ERROR: convert_to_yaml.py is out of sync with C++ enums.', file=sys.stderr)
        print('Run: python3 tools/converter/regenerate_flag_tables.py', file=sys.stderr)
        return 1

    TARGET.write_text(expected, encoding='utf-8')
    print(f'convert_to_yaml.py: rewrote AUTOGENERATED flag tables ({len(block.splitlines())} lines).')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
